### ISSUE TITLE
Function app deployment fails

### ISSUE THREAD

**Issue by kszicsillag** [MicrosoftDocs/mslearn-apim-and-functions#1]
I am following the ms learn [module](https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/3-exercise-import-function-app-api-management) in the sandbox, but [/setup.sh](../blob/master/setup.sh) fails at `az functionapp deployment` with the following error:

```
'NoneType' object has no attribute 'server_farm_id'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 316, in enable_zip_deploy_functionapp
    parse_plan_id = parse_resource_id(app.server_farm_id)
AttributeError: 'NoneType' object has no attribute 'server_farm_id'
```

**Comment by kszicsillag** [comment]
Maybe related: https://github.com/Azure/azure-cli/issues/10773

**Comment by nickwalkmsft** [comment]
Thanks for reporting, although I was unable to reproduce.

Could it be that creation of one or both function apps failed first, and then resulted in this? I *did* experience *that* while attempting to repro (complains about scale functionality not supported in region), and changed the region used by the script to `centralus` to reflect internal best practices for our sandbox usage and fix (or at least improve) reliability there.

I will keep this open for now.

**Comment by kszicsillag** [comment]
Given it another try and it looks like it was an intermittent issue (or the region change fixed it).
